version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
#  - Debug

platform:
  - x86
#  - x64

artifacts:
  - path: 'Release\WinNetworkMeterSample.exe'
  - path: 'CHANGELOG.md'

cache:
  - C:/Ruby25/lib/ruby/gems/2.5.0/
  - C:/Ruby25/bin

after_build:
  - set PATH=C:\Ruby25\bin;%PATH%
  - ruby --version
  - where ruby
  - dir C:\Ruby25\bin
  - dir C:\Ruby25\lib\ruby\gems\2.5.0\
  - gem install github_changelog_generator
  - dir C:\Ruby25\lib\ruby\gems\2.5.0\
  - mkdir c:\tmp
#  - github_changelog_generator -u takke -p WinNetworkMeterSample
  - github_changelog_generator -u sakura-editor -p sakura --exclude-labels duplicate,question,invalid,wontfix,CI,management,refactoring
