version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
#  - Debug

platform:
  - x86
#  - x64

artifacts:
  - path: 'Release\WinNetworkMeterSample.exe'
  - path: 'CHANGELOG.md'

after_build:
  - set PATH=C:\Ruby25\bin;%PATH%
  - ruby --version
  - where ruby
  - gem install github_changelog_generator
  - mkdir c:\tmp
#  - github_changelog_generator -u takke -p WinNetworkMeterSample
  - echo %CHANGELOG_GITHUB_TOKEN%
  - github_changelog_generator -u sakura-editor -p sakura --exclude-labels duplicate,question,invalid,wontfix,CI
